services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: target-server-1   # change per host
    pid: host
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports: ["9100:9100"]
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log:ro
    restart: unless-stopped
